name: transformer
type: model_B # Corresponds to the imports in full_pipeline.py

# Model configuration
xperiment:
  name: "${experiment_name}_transformer" # Will use the experiment_name from the main config
  model: "time_series" # Default model type, can be "time_series" or "simple_encoder"

data:
  data_file_name: "big_imputed_sofa"
  use_last_processed_data: true
  sampling: true
  sampling_method: "oversample"
  sampling_minority_ratio: 0.3
  train_sample_fraction: 1.0
  test_size: 0.2
  random_state: ${random_seed} # Use the global random seed

model:
  d_model: 128
  num_heads: 4
  num_layers: 2
  drop_out: 0.2

training:
  batch_size: 32
  use_post_weight: true
  max_post_weight: 5
  lr: 0.001
  epochs: 100

testing:
  batch_size: 32
