num_epochs: 50
batch_size: 64
early_stopping: true
patience: 10
learning_rate: 0.001
optimizer: "adam"
loss: "binary_crossentropy"
metrics: ["accuracy", "auc", "precision", "recall"]

# Logging and checkpoints
save_best_model: true
log_frequency: 10
