xperiment:
  name: "05_encoder_transformer"
  model: "simple_encoder"

data:
  data_file_name: "big_imputed_sofa"
  use_last_processed_data: True
  sampling: True
  sampling_method: "undersample"
  sampling_minority_ratio: 0.5
  train_sample_fraction: 0.5
  test_size: 0.2
  random_state: 42

model:
  num_heads: 2
  num_layers: 2
  drop_out: 0.1

training:
  batch_size: 32
  use_post_weight: True
  max_post_weight: 5
  lr: 0.001
  epochs: 100
  threshold_update_n_batches: -1

testing:
  batch_size: 32