xperiment:
  name: "22_our_oversampled_5050_dsv4_mf_256_8_4"
  model: "time_series"

data:
  data_file_name: "dsv4"
  use_last_processed_data: false
  sampling: true
  sampling_method: oversample
  sampling_minority_ratio: 0.5
  train_sample_fraction: 1
  test_size: 0.2
  random_state: 42

model:
  d_model: 256
  num_heads: 8
  num_layers: 4
  drop_out: 0.25

training:
  batch_size: 256
  use_post_weight: true
  max_post_weight: 5
  lr: 0.0001
  epochs: 1000

testing:
  batch_size: 256
