xperiment:
  name: '11_downsampled_64_4_1'
  model: 'time_series'

data:
  data_file_name: 'preprocessed_data'
  use_last_processed_data: true
  sampling: true
  sampling_method: undersample
  sampling_minority_ratio: 0.3
  train_sample_fraction: 1
  test_size: 0.2
  random_state: 42

model:
  d_model: 64
  num_heads: 4
  num_layers: 1
  drop_out: 0.1

training:
  batch_size: 128
  use_post_weight: true
  max_post_weight: 5
  lr: 0.001
  epochs: 1000

testing:
  batch_size: 32
