xperiment:
  name: "06_time_series_transformer"
  model: "time_series"

data:
  data_file_name: "big_imputed_sofa"
  use_last_processed_data: true
  sampling: true
  sampling_method: undersample
  sampling_minority_ratio: 0.3
  train_sample_fraction: 1
  test_size: 0.2
  random_state: 42

model:
  d_model: 64
  num_heads: 2
  num_layers: 2
  drop_out: 0.1

training:
  batch_size: 32
  use_post_weight: true
  max_post_weight: 5
  lr: 0.001
  epochs: 100

testing:
  batch_size: 32