xperiment:
  name: '14_undersampled_64_2_1'
  model: 'time_series'

data:
  data_file_name: 'V2_preprocessed'
  use_last_processed_data: false
  sampling: true
  sampling_method: undersample
  sampling_minority_ratio: 0.3
  train_sample_fraction: 0.5
  test_size: 0.2
  random_state: 42

model:
  d_model: 64
  num_heads: 2
  num_layers: 1
  drop_out: 0.2

training:
  batch_size: 64
  use_post_weight: true
  max_post_weight: 1000
  lr: 0.001
  epochs: 1000

testing:
  batch_size: 64
