xperiment:
  name: "03_encoder_transformer"

data:
  data_file_name: "big_imputed_sofa"
  use_last_processed_data: False
  sampling: True
  sampling_method: "oversample"
  sampling_minority_ratio: 0.3
  train_sample_fraction: 0.1
  test_size: 0.2
  random_state: 42

model:
  num_layers: 2
  drop_out: 0.1

training:
  batch_size: 32
  use_post_weight: True
  max_post_weight: 5
  lr: 0.001
  epochs: 100
  threshold_update_n_batches: -1

testing:
  batch_size: 32